variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "aws_region" {}
# variable "s3-name" {}
variable "vpc_cidr" {}
variable "vpc_name" {}
variable "owner_name" {}
variable "environment" {}
variable "IGW_name" {}
variable "EIP_name" {}
variable "NAT_name" {}
variable "public_subnet1_cidr" {}
variable "public_subnet2_cidr" {}
variable "public_subnet3_cidr" {}
variable "private_subnet1_cidr" {}
variable "private_subnet2_cidr" {}
variable "private_subnet3_cidr" {}
variable "public_subnet1_name" {}
variable "public_subnet2_name" {}
variable "public_subnet3_name" {}
variable "private_subnet1_name" {}
variable "private_subnet2_name" {}
variable "private_subnet3_name" {}
variable "Main_Routing_Table" {}
variable "private_Table" {}
variable "SG1_name" {}
variable "inbound_source" {}